// Generated by CoffeeScript 1.7.1
(function() {
  var app, express, fs, path, favicon, mongo, monk, db, routes;

  express = require('express');

  fs = require('fs');

  path = require('path');

  favicon = require('serve-favicon');

  mongo = require('mongodb');

  monk = require('monk');

  db = monk('localhost:27017/pre');

  routes = require('./routes/index');

  app = express();

  app.set('views', path.join(__dirname, 'views'));

  app.set('view engine', 'jade');

  app.use(express["static"]('public'));

  app.use(favicon(path.join(__dirname,'/public/img/favicon.ico')));

  app.use(function(req,res,next) {
    req.db = db;
    next();
  });

  app.use('/', routes);

  app.listen(3000);

  console.log("hello?");

}).call(this);
