// Generated by CoffeeScript 1.7.1
(function() {
  var app, express, fs, path, favicon;

  express = require('express');

  fs = require('fs');

  path = require('path');

  favicon = require('serve-favicon');

  app = express();

  app.set('views', path.join(__dirname, 'views'));

  app.set('view engine', 'jade');

  app.use(express["static"]('public'));

  app.use(favicon(path.join(__dirname,'/public/img/favicon.ico')));

  app.get('/yesno', function(req, res) {
    return res.render('ynpoll');
  });

  app.get('/yesnob', function(req, res) {
    return res.render('ynpollb');
  });

  app.listen(3000);

}).call(this);
